title: Coleção A11Y
description: Conteúdos formativos sobre acessibilidade web
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Define Jekyll collections

collections:
  legis:
    permalink: "/legis/:path/"    
    output: true
  html:
    permalink: "/html/:path/"    
    output: true
  images:
    permalink: "/images/:path/"
    output: true
  forms:
    permalink: "/forms/:path/"    
    output: true
    

just_the_docs:
  collections:
    legis:
      name: 1. Legislação
      nav_fold: true
    html:
      name: 2. Semântica HTML
      nav_fold: true
    images:
      name: 6. Imagens
      nav_fold: true
    forms:
      name: 8. Formulários
      nav_fold: true
