title: Coleção A11Y
description: Conteúdos formativos sobre acessibilidade web
theme: just-the-docs

url: https://amagovpt.github.io/collection-a11y

aux_links:
  Template Repository: https://github.com/amagovpt/collection-a11y

kramdown:
  input: GFM
  toc_levels: 2..2

# Define Jekyll collections

collections:
  legis:
    permalink: "/legis/:path/"    
    output: true
  html:
    permalink: "/html/:path/"    
    output: true
  text:
    permalink: "/text/:path/"    
    output: true
  visual:
    permalink: "/visual/:path/"    
    output: true  
  menus:
    permalink: "/menus/:path/"    
    output: true    
  images:
    permalink: "/images/:path/"
    output: true
  tables:
    permalink: "/tables/:path/"
    output: true    
  forms:
    permalink: "/forms/:path/"    
    output: true
  media:
    permalink: "/media/:path/"
    output: true 
  widgets:
    permalink: "/widgets/:path/"
    output: true   
  aria:
    permalink: "/aria/:path/"
    output: true   
  nonweb:
    permalink: "/nonweb/:path/"
    output: true        

just_the_docs:
  collections:
    legis:
      name: Curso 1. Normas e Diretrizes
      nav_fold: true
    html:
      name: Curso 2. Estrutura 
      nav_fold: true
    text:
      name: Curso 3. Texto
      nav_fold: true   
    visual:
      name: Curso 4. Desenho Visual
      nav_fold: true  
    menus:
      name: Curso 5. Menus
      nav_fold: true      
    images:
      name: Curso 6. Imagens
      nav_fold: true
    tables:
      name: Curso 7. Tabelas
      nav_fold: true
    forms:
      name: Curso 8. Formulários
      nav_fold: true
    media:
      name: Curso 9. Multimédia
      nav_fold: true
    widgets:
      name: Curso 10. Widgets
      nav_fold: true
    aria:
      name: Curso 11. ARIA
      nav_fold: true  
    noweb:
      name: Curso 12. Outros Docs
      nav_fold: true      
